spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1142165668
  jpa:
    # 更新表结构
    hibernate:
      ddl-auto: none
    # 日志中是否显示sql语句
    show-sql: true

# 日志的级别
logging:
  level:
    root: warn
    com.zr.blog: info
  file:
    name: log/blog-pro.log
server:
    port: 8081